1st review
PalomoBravas/React pull request #1
Opened 2023-08-03 14:10 UTC by PalomoBravas

2023-08-05 11:14 UTC, Grinv requested changes

2023-08-05 11:14 UTC, Grinv commented on my-blog/app/page.tsx
> +import './globals.css'
Зачем тут? Ты ж уже импортировал в layout файле)

2023-08-05 11:14 UTC, Grinv commented on my-blog/app/layout.tsx
> +const ptSans = PT_Sans({ subsets: ['latin'], weight: ['400', '700'] })
Вообще советую прописать шрифт в css переменную, как сделано тут https://nextjs.org/learn/basics/assets-metadata-css/global-styles
и в global.css уже прописать в body переменную

2023-08-05 11:14 UTC, Grinv commented on my-blog/components/Card/card.tsx
> +                src='/29CCWU6H.jpg'
Лучше импортировать, как файл. Так кэш лучше работает
```javascript
import cardImageUrl from `@public/images/29CCWU6H.jpg`
// ...
<Image
   className={styles.coverImage}
   src={cardImageUrl}
   width='500'
   height='300'
   alt='cover image'
/>

2023-08-05 11:14 UTC, Grinv commented on my-blog/components/Card/card.tsx
> +                <LikeButton countLike = {5} pressed = {false}/>
Не нужны пробелы до и после `=` :)

2023-08-05 11:14 UTC, Grinv commented on my-blog/components/Card/card.tsx
> +                    <img src="/icon/arrow.svg" alt="rightArrow" />
Надо перенести в `/public/icons` и экспортировать через `Image`

2023-08-05 11:14 UTC, Grinv commented on my-blog/components/Card/card.tsx
> +                <span className={styles.timeRead}> 3 minutes </span>
Ненужные пробелы

2023-08-05 11:14 UTC, Grinv commented on my-blog/components/Card/card.tsx
> +        <section className={styles.card}>
Всякие карточки лучше оборачивать в тэг article
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article
>Examples include: a forum post, a magazine or newspaper article, or a blog entry, a product card, a user-submitted comment, an interactive widget or gadget, or any other independent item of content.

2023-08-05 11:14 UTC, Grinv commented on my-blog/components/SVG-Icons/like.tsx
> +export default LikeButtonIcon
Не надо как компонент. Пожалейте оптимизацию) Это должен быть обычный файл `like.svg`, который мы должны импортировать, как иконку.
Если что-то нужно что-то изменить внутри - меняем через навешивание класса с нужными стилями.

2023-08-05 11:14 UTC, Grinv commented on my-blog/components/LikeButton/like-button.tsx
> +import LikeButtonIcon from "../SVG-Icons/like";
Перенести в `/public/icons` и переделать из компонента в обычную svg иконку

2023-08-05 11:14 UTC, Grinv commented on my-blog/components/LikeButton/like-button.module.css
> +    padding-top: 3px;
А зачем тут пэддинг?) У тебя ж отцентрирована иконка)

2023-08-10 12:06 UTC, PalomoBravas commented on my-blog/components/SVG-Icons/like.tsx
> +export default LikeButtonIcon
Вот тут не совсем понятно - если как Image - то навесить класс на svg уже не получается: так как в верстке тег img а не svg

2023-08-10 12:27 UTC, PalomoBravas commented on my-blog/components/LikeButton/like-button.tsx
> +import LikeButtonIcon from "../SVG-Icons/like";
Переделал, поискал но все равное не понял как динамически менять svg свойства у встроенного компонента Image

2023-08-10 12:39 UTC, PalomoBravas commented on my-blog/components/Card/card.tsx
> +                src='/29CCWU6H.jpg'
А если картинки добавляются динамически что чаще бываетЮ то как тогда их импортировать, в отдельный файл: а потом из него?

2023-08-11 06:48 UTC, Grinv commented on my-blog/components/Card/card.tsx
> +                src='/29CCWU6H.jpg'
Что имеешь ввиду под динамически? Что мы заранее не знаем ссылки на картинку, которая придёт?
Тогда только как ссылку. Некст к себе её загрузит, трансформирует как надо и выдаст на клиент уже свою версию.

2023-08-11 06:49 UTC, Grinv commented on my-blog/components/SVG-Icons/like.tsx
> +export default LikeButtonIcon
А зачем тебе вешать класс на svg? Вешай на img

2023-08-11 06:49 UTC, Grinv commented on my-blog/components/LikeButton/like-button.tsx
> +import LikeButtonIcon from "../SVG-Icons/like";
А какие свойства тебе надо менять?
Если размер - это делает спокойно через img
Если надо менять цвет path например, то да, через img тогда не получится, вставляй тогда img как компонент, навешивай класс и через класс изменяй

2023-08-11 07:03 UTC, Grinv requested changes

2023-08-11 07:03 UTC, Grinv commented on my-blog/app/layout.tsx
> +const ptSans = PT_Sans({ subsets: ['latin'], weight: ['400', '700'] })
Сорри, ссылку не ту дал. Имел ввиду как вот в этом примере добавить css переменную: 
https://nextjs.org/docs/pages/api-reference/components/font#css-variables

2023-08-11 07:03 UTC, Grinv commented on my-blog/components/Card/card.tsx
> +import arrowImageUrl from '../../public/icon/arrow.svg'
Давай сделаем алиас для public, чтоб мы могли писать например так
```javascript
import arrowImageUrl from '@/public/icon/arrow.svg'

2023-08-11 07:03 UTC, Grinv commented on my-blog/components/Card/card.module.css
> +    background: var(--c-white, #FFF);
Зачем тут #FFF? --c-white этим цветом и является
А ещё у тебя самым первым свойством прописано `background: darkolivegreen;`
Удали пожалуйста один из них

2023-08-11 07:03 UTC, Grinv commented on my-blog/components/Card/card.module.css
> +    border: 1px solid var(--c-border, #F5F5F5);
```css
border: 1px solid var(--c-border);

2023-08-11 07:03 UTC, Grinv commented on my-blog/components/LikeButton/like-button.tsx
> +                src={pressed ? likeIconRedURL : likeIconGrayURL}
Да, если ты имел ввиду это место, как модифицировать, то тут тогда надо будет отказаться от Image и использовать svg как объект с классом и при hover менять fill

2023-08-14 06:52 UTC, Grinv approved these changes

2023-08-14 06:52 UTC, merged