3 ssr
PalomoBravas/React pull request #3
Opened 2023-09-06 10:02 UTC by PalomoBravas

2023-09-06 10:04 UTC, PalomoBravas commented
Не понимаю как вставлять svg! Могу как компонент, могу как image (но тогда это уже не svg) а как просто импортировать и вставить не понимаю(

2023-09-08 09:04 UTC, SergeyKrasnolobov commented
Привет, а почему ты не назначаешь наставника на ревью?

2023-09-08 09:04 UTC, SergeyKrasnolobov commented
У тебя в ревьюерах никого нет

2023-09-08 10:02 UTC, Grinv requested changes

2023-09-08 10:02 UTC, Grinv commented on my-blog/api.tsx
> +        getPostById: process.env.NEXT_PUBLIC_DOMAIN + '/posts/'
У тебя же тут один и тот же url
Лучше сделать так
```jsx
post: {
    get: process.env.NEXT_PUBLIC_DOMAIN + '/posts',
}
```
query params мы не хардкорим в урле, нужно оставлять возможность их кастомизировать

2023-09-08 10:02 UTC, Grinv commented on my-blog/app/(site)/post/[id]/layout.module.css
> +    width: 1216px;
А если экран будет шириной меньше 1216px? Появится горизонтальный скролл. Это не есть хорошо
Всегда думай о других устройствах)
Лучше задать так:
```css
width: 100%;
max-width: 1216px;

2023-09-08 10:02 UTC, Grinv commented on my-blog/app/(site)/post/[id]/page.tsx
> +    description: 'about',
Как правило title и description отличаются. description описывает более детально, о чём страница.
Если title и description одинаковые, то лучше вообще description убрать. Но лучше для SEO описать

2023-09-08 10:02 UTC, Grinv commented on my-blog/components/Header/header.tsx
> +                alt='Логотип сайты скрытый цвет'/>
Я уже запутался, у тебя в хэдере 2 картинки с описанием "лого" и одинаковым alt. Лучше всё-таки поменять, чтоб описание соответствовало смыслу

2023-09-08 10:02 UTC, Grinv commented on my-blog/components/LikeButton/like_button.tsx
> +            мне же нужно вставить его в код именно как <svg>*/}
У тебя же в хэдере импортируется так svg
```jsx
import siteLogoUrl from "@/public/logo/HIDDEN COLOR.svg";
```
Сделай по подобию

2023-09-08 10:02 UTC, Grinv commented on my-blog/components/PostList/postList.module.css
> +    width: calc(1/3 * 100%);
Если тебе нужна плитка из постов, я бы рекомендовал всё-таки использовать grid для этого.
```css
.postList {
   display: grid;
   grid-template-columns: 1fr 1fr 1fr;
}
```
Тогда в `.post` не придётся считать ширину каждого элемента

2023-09-08 10:02 UTC, Grinv commented on my-blog/components/PostList/postList.tsx
> +                <button className={styles.readButton}>
Вставлять кнопку в ссылку - семантически неверно.
https://caninclude.glitch.me/caninclude?child=button&parent=a

Если хочется эмуляцию кнопки - просто сделаю внутри элемент span или div со свойствами кнопки

2023-09-08 10:02 UTC, Grinv commented on my-blog/services/GetData.tsx
> +    let url = countPosts!==0 && countPosts<100 ? `${API.post.getLimit}${countPosts}` : `${API.post.getAll}`
1) У нас тут везде должен использоваться `API.post.get`
2) Почему этот метод называется getData, а другой getPost. Разве мы тут тоже не фетчим посты?

Предлагаю сделать 2 отдельных метода: `getPosts`, `getPostById`

И в getPosts ты уже разруливаешь, добавлять limit query params к ссылке или нет

2023-09-13 14:45 UTC, PalomoBravas commented on my-blog/components/LikeButton/like_button.tsx
> +            мне же нужно вставить его в код именно как <svg>*/}
Если я сделаю по подобию он встанет в верстку с тегом img и я опять не смогу пользоваться его css свойствами. Я бы его сделал отеделным компонентом, но это мы уже проходили. Поэтому я и не понимаю как его вставить чтобы он сохранил тег svg и был при этом не компанентом.

2023-09-19 07:18 UTC, Grinv requested changes

2023-09-19 07:18 UTC, Grinv commented on my-blog/app/(site)/post/[id]/page.tsx
> +
Зачем столько пробелов?)

2023-09-19 07:18 UTC, Grinv commented on my-blog/app/(site)/post/[id]/page.tsx
> +
Очень советую посмотреть и почитать про prettier. Супер удобная вещь при разработке, автоматически форматирует код
https://prettier.io

2023-09-19 07:18 UTC, Grinv commented on my-blog/app/page.tsx
> +    console.log()
Забыл убрать

2023-09-19 07:18 UTC, Grinv commented on my-blog/components/Article/article.module.css
> +;
Зачем `;`
Лишний мусор

2023-09-19 07:18 UTC, Grinv commented on my-blog/components/Article/article.tsx
> +            <span></span>
А тут span зачем?

2023-09-19 07:18 UTC, Grinv commented on my-blog/components/Card/card.tsx
> +                    href={'/post/2'}
У тебя тут пост захардкожен. Мы же в каждой карточке на свой пост ссылаемся, правильно?)

2023-09-19 07:18 UTC, Grinv commented on my-blog/services/getPosts.tsx
> +    console.log('getData ' + countPosts + url )
Забыл убрать console.log

2023-09-19 07:18 UTC, Grinv commented on my-blog/components/Header/header.tsx
> +        <AppContextProvider url='https://www.blackmagicdesign.com/'>
Вообще я не очень понял смысла этого контекста. Он у тебя проходит через всё приложение с одной ссылкой. А в итоге используется только в хэдере. Хотя ты мог бы просто задать его в компоненте LogoLink
```jsx
<Link href="https://www.blackmagicdesign.com" target='_blank'>
```
И в итоге упростил бы логику.

2023-09-19 07:18 UTC, Grinv commented on my-blog/components/Header/header.tsx
> +const LogoLink = () => {
Не очень удачно выбрано имя. Это всё-таки в первую очередь ссылка, а не лого)

2023-09-19 07:18 UTC, Grinv commented on my-blog/components/Header/header.tsx
> +                <Link href='/'>
Это ссылка является частью навигации? Кажется, что да. Тогда давай её тоже в тэг nav перенесём)

2023-09-19 07:18 UTC, Grinv commented on my-blog/components/LikeButton/like_button.tsx
> +            мне же нужно вставить его в код именно как <svg>*/}
Смотри. Если тебе из свойств надо менять размер - это спокойно делается через img
Если нужно поменять цвет. Тут либо ты можешь попробовать сделать через filter
https://developer.mozilla.org/en-US/docs/Web/CSS/filter
https://angel-rs.github.io/css-color-filter-generator
Если нужна анимация - я предпочитаю анимацию прям внутрь svg зашивать.
Если с цветом не выходит или не работает - тогда да, нам придётся всё-таки вставлять svg инлайново как компонент (как сделано у тебя). Нужно будет сюда вставить `<LikeIcon />`, либо воспользоваться webpack/svgr (https://react-svgr.com/docs/webpack/), но он по сути сделает тоже самое, только автоматизированно.

2023-09-19 07:18 UTC, Grinv commented on my-blog/components/LikeButton/like_button.tsx
>              <svg
У тебя же уж есть компонент для этого) (который `my-blog/components/likeIcon.tsx`)
Давай им воспользуемся
```jsx
<LikeIcon />

2023-09-19 07:18 UTC, Grinv commented on my-blog/components/PostList/postList.tsx
> +import getData from "@/services/getPosts";
Назови метод также `getPosts`. Зачем менять? В данном примере в этом нет смысла и это только усложняет чтение.

2023-09-21 14:45 UTC, PalomoBravas commented on my-blog/components/Header/header.tsx
> +        <AppContextProvider url='https://www.blackmagicdesign.com/'>
Я вообще не понял смысла контекста в данном проекте. НО это было задание Антона попробовать сделать контекст.

2023-09-21 15:02 UTC, PalomoBravas commented on my-blog/components/Header/header.tsx
> +                <Link href='/'>
Нет, это ссылка не является навигацией, это логотип сайта с функцией возврата на главную. Просто в этом проекте в <nav> ущербная навигация(

2023-09-24 07:44 UTC, Grinv approved these changes

2023-09-24 07:44 UTC, Grinv commented on my-blog/components/Article/article.tsx
> +
Куча ненужных пустых строк осталась)

2023-09-24 07:44 UTC, merged